version: '3'

services:
  app:
    container_name: chat_app_backend_app
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    ports:
        - '9000:9000'
    restart: always
    tty: true
    volumes:
      - .:/var/www
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      PHP_EXTENSION_XDEBUG: 1
      XDEBUG_CONFIG: remote_host=10.101.0.35 # ip máy local
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: chat_app_nginx
    restart: always
    tty: true
    ports:
        - '8080:80'
        - '8043:443'
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
  mysql:
      image: mysql:5.7
      container_name: chat_app_mysql
      restart: always
      build:
          context: ./docker/mysql
          dockerfile: Dockerfile
      networks:
          - app_network
      ports:
          - '3390:3306'
      volumes:
          - ./docker/mysql/data:/var/lib/mysql

  phpmyadmin:
          image: phpmyadmin/phpmyadmin
          links:
              - mysql
          environment:
              PMA_HOST: mysql
              PMA_PORT: 3306
              PMA_ARBITRARY: 1
          restart: unless-stopped
          depends_on:
              - mysql
          ports:
              - "8082:80"
          networks:
              - app_network

networks:
  app_network:
    driver: bridge
